"""composite index added

Revision ID: 3ea05e33cae5
Revises: a8935e76c451
Create Date: 2026-09-11 11:07:55.167826

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ea05e33cae5"
down_revision: str | Sequence[str] | None = "a8935e76c451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_posts_created_at_id",
        "posts",
        ["created_at", "id"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_created_at_id", table_name="posts", postgresql_using="btree")
    # ### end Alembic commands ###
