"""index added to created_at

Revision ID: a8935e76c451
Revises: 6095844e118b
Create Date: 2026-09-05 05:06:55.798544

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8935e76c451"
down_revision: str | Sequence[str] | None = "6095844e118b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_posts_created_at"), "posts", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_created_at"), table_name="posts")
    # ### end Alembic commands ###
