services:

  postgres:
      image: postgres:17
      container_name: cursor_offset_db
      env_file: 
        .env.local
      ports:
        - "6432:5432"  
      volumes:
        - cursor_offset_data:/var/lib/postgresql/data
      # networks:
      #   - marketplace_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  test_db:
      image: postgres:17
      container_name: test_db
      env_file: 
        .env.test
      ports:
        - "16432:5432"  
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  locust:
      image: postgres:17
      container_name: locust_db
      env_file: 
        .env.locust
      ports:
        - "26432:5432"  
      volumes:
        - locust_db_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped


volumes:
  cursor_offset_data:
  locust_db_data:
