services:
 
  # marketplace:
  #   build: .
  #   container_name: marketplace_app
  #   env_file: .env.prod
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - marketplace_network
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"

  postgres:
      image: postgres:17
      container_name: cursor_offset_db
      env_file: 
        .env.local
      ports:
        - "6432:5432"  
      volumes:
        - cursor_offset_data:/var/lib/postgresql/data
      # networks:
      #   - marketplace_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  test_db:
      image: postgres:17
      container_name: test_db
      env_file: 
        .env.test
      ports:
        - "16432:5432"  
      # volumes:
      #   - cursor_offset_data:/var/lib/postgresql/data
      # networks:
      #   - marketplace_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped


volumes:
  cursor_offset_data:
