name: tests

on:
  push:
      branches: [master]
  pull_request:
      branches: [master]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            version: "latest"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Cache uv and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-venv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-venv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Type check with mypy
        run: uv run mypy .

      - name: Prepare .env.local file
        run: |
          cat > .env.example.local <<'EOF'
          ENVIRONMENT=LOCAL
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=cursor_offset_local
          DB_HOST=localhost
          DB_PORT=6432
          EOF
          cp .env.example.local .env.local

      - name: Prepare .env.test file
        run: |
          cat > .env.example.test <<'EOF'
          ENVIRONMENT=TEST
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=cursor_offset_test
          DB_HOST=localhost
          DB_PORT=16432
          EOF
          cp .env.example.test .env.test

      - name: Start DataBase
        run: docker compose up -d

      - name: Run tests
        run: uv run pytest --cov=app --cov-report=html --cov-fail-under=90

      - name: Stop Containers
        if: always()
        run: docker compose down -v
